prevent duplicate targets: rename NIOHTTP1Client to NIOSSLHTTP1Client
Motivation:

With package editing this problem surfaces:

```
$ jw-swift-5.0 swift test
error: multiple products named 'NIOHTTP1Client' in: swift-nio, swift-nio-ssl
error: multiple targets named 'NIOHTTP1Client' in: swift-nio, swift-nio-ssl
```

which is bad. Fortunately, these are executable targets that we can
rename.

Modification:

rename `NIOHTTP1Client` in swift-nio-ssl to `NIOSSLHTTP1Client`

Result:

usable with package editing.